spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://therapia-database.cgtyvvaod34a.ap-northeast-2.rds.amazonaws.com:3306/therapia
    username: admin
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
      format_sql: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
server:
  port: 80