spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://therapia-1.cgtyvvaod34a.ap-northeast-2.rds.amazonaws.com:3306/therapiadb
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
      format_sql: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace