server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active:
      - prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
      format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always